data:
  type: 'kaggle_library_book'
  base_path: 'data/'
  raw_data_path: 'kaggle_library_books/'
  processed_path: 'kaggle_library_books_processed_data'
  testset_size: 22996
  num_classes: 5
  PAD_ID: 0

model:
  batch_size: 64
  embed_type: 'rand'     #(rand, static, non-static, multichannel)
  pretrained_embed: ""
  embed_dim: 300
  num_filters: 256
  filter_sizes:
    - 2
    - 3
    - 4
    - 5
  dropout: 0.5

train:
  learning_rate: 0.00005

  train_steps: 100000
  model_dir: 'logs/kaggle_library_book'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

  print_verbose: True
  debug: False

slack:
  webhook_url: ""
